### PR TITLE
add dnd

### PR DESCRIPTION
**Pull request by adrianthedev**
I wasn't able to make the arrow buttons pretty and compact, so I added drag and drop.
Can you see if it works nicely on your end and then merge it to your PR?

### CODE REVIEW

**Comment by adrianthedev** [comment]
Please hold off merging a little bit. I found a bug.

**Comment by adrianthedev** [comment]
@enderahmetyurt The sorting algo isn't working properly sometimes.
I can't have a look right now. Would you be able to check that out?


https://github.com/user-attachments/assets/52ff8bb6-37a8-4220-8459-5d00c4ed8446

**Comment by enderahmetyurt** [comment]
Hey @adrianthedev thank you. I will look at it

**Comment by enderahmetyurt** [comment]
it looks fine @adrianthedev

**Comment by adrianthedev** [comment]
In the video you can see that the drag and drop work to switch places (when we drag the one under the four, it takes the four in the place of the one instead of just placing the one below the four) instead of regular drag and drop where you reorder items.

So the intended result should have been "two, three, four one", but now it's "four, two, three, one".

**Comment by enderahmetyurt** [comment]
hmm I missed it. I can control and try to fix it here https://github.com/avo-hq/avo/pull/3299 or I can get back it

**Comment by adrianthedev** [comment]
Yeah, it's fine to fix it there. I couldn't push to that branch, that's why I made this PR.

**Pull request merged**
